default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
gplus-theme: styles/gplus-theme-for-mastodon.scss
gplus-theme-schwarz: styles/gplus-theme-schwarz.scss
